TEST_PARSED_INPUT	= test_parsed_input/test_parsed_input.c \
						$(SRC)set_input.c $(SRC)utils.c

ABSOLUTE_PATH		= /Users/pmarash/42/philo/Eat-sleep-die/

SRC					= $(ABSOLUTE_PATH)srcs/

FLAGS				= -Wall -Wextra -Werror -g

parsed_input:
	gcc $(FLAGS) -o parsed_input $(TEST_PARSED_INPUT)

clean_all:
	rm -rf parsed_input